server:
  port: 8083

spring:
  application:
    name: ms-products
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    password: password
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
