server:
  port: 8082

spring:
  application:
    name: ms-products
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/challenge03
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false